var studentData = [
    {
        "number": 1,
        "alias": "Aldor",
        "hobbytext": "I have great interest in visual design and filmmaking. ",
        "hobbycreative": 1,
        "hobbygraphics": 1,
        "hobbydesign": 1,
        "skillivis": 7,
        "skillstats": 3,
        "skillmath": 3,
        "skillart": 9,
        "skilluser": 6,
        "skillprog": 2,
        "skillgraphics": 1,
        "skillhci": 4,
        "skillux": 8,
        "group": 1,
        "groupindex": 1,
        "top": "ivis",
        "learning": "I expect to learn the why, how and what of the visualization of data. Thinking of the why in order to create meaningful visualizations and the how & what to learn the programming and design that is involved. "
    },
    {
        "number": 2,
        "alias": "Aragorn",
        "hobbytext": "I have been an aviation enthusiast since I was a kid, although I do not hold a pilot's license (yet). I enjoy cooking and I try to follow a healthy lifestyle with regular physical activity, such as cycling, running or team sports, mostly football. I have developed an increasing interest in all sorts of water-sports over the past few years, mostly in free-diving and surfing. I have an appreciation for all art forms but I am far from being an art-savvy. ",
        "hobbycreative": 1,
        "hobbyphysical": 6,
        "hobbyfood": 1,
        "skillivis": 5,
        "skillstats": 4,
        "skillmath": 3,
        "skillart": 6,
        "skilluser": 7,
        "skillprog": 3,
        "skillgraphics": 1,
        "skillhci": 4,
        "skillux": 8,
        "group": 4,
        "groupindex": 1,
        "top": "ux",
        "learning": "I am working on several personal projects that I expect to translate into business ideas. A good design is a key point for the success of these ideas, so I expect that I can apply what I learn in this course to seduce potential users with a jaw-dropping representation of data."
    },
    {
        "number": 3,
        "alias": "Arwen",
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 3,
        "skillart": 3,
        "skilluser": 8,
        "skillprog": 8,
        "skillgraphics": 3,
        "skillhci": 3,
        "skillux": 3,
        "group": 8,
        "groupindex": 1,
        "top": "prog",
        "learning": "How to design systems which are more user-centered."
    },
    {
        "number": 4,
        "alias": "Balin",
        "hobbytext": "Some hobbies would be graphic design and 3D modeling.",
        "hobbygraphics": 2,
        "skillivis": 3,
        "skillstats": 4,
        "skillmath": 4,
        "skillart": 6,
        "skilluser": 8,
        "skillprog": 2,
        "skillgraphics": 1,
        "skillhci": 2,
        "skillux": 7,
        "group": 5,
        "groupindex": 1,
        "top": "hci",
        "learning": "To be honest I am not quite sure. Seems like a good course for combining \"pretty\" with \"tech\". "
    },
    {
        "number": 5,
        "alias": "Bereg",
        "hobbytext": "Science, sports, fashion, travel",
        "hobbyphysical": 1,
        "hobbytravel": 1,
        "hobbyscience": 1,
        "skillivis": 3,
        "skillstats": 5,
        "skillmath": 6,
        "skillart": 8,
        "skilluser": 6,
        "skillprog": 3,
        "skillgraphics": 5,
        "skillhci": 3,
        "skillux": 5,
        "group": 5,
        "groupindex": 2,
        "top": "art",
        "learning": "To handle and present information in a structured way."
    },
    {
        "number": 6,
        "alias": "Bifur",
        "hobbytext": "25 year old student doing my 4th/5th year. I'm outgoing as a person and I like to learn new things and challenge myself. Recently took a gap year traveling in Asia and later on studying in Australia. I like graphic illustration, I'm self-taught and it's more of a hobby. Otherwise I've recently started going to events/hackatons in my spare time. Mostly related to helping organisations develop ideas and prototypes by the use of technology. Also looking forward to the Crash Bandicoot on PS4 game release!",
        "hobbycreative": 1,
        "hobbypsychology": 2,
        "hobbyprogramming": 1,
        "skillivis": 4,
        "skillstats": 4,
        "skillmath": 5,
        "skillart": 6,
        "skilluser": 10,
        "skillprog": 7,
        "skillgraphics": 7,
        "skillhci": 6,
        "skillux": 7,
        "group": 10,
        "groupindex": 1,
        "top": "art",
        "learning": "Learn: New programming skills, new softwares, learning different visualization methods, being able to more easily see what model is most relevant for showing the data. Teambuilding.\nFuture: Use it when analyzing and selling. I want to run my own business some day and this is a great tool to have. "
    },
    {
        "number": 7,
        "alias": "Bilbo",
        "hobbytext": "JavaScript interests me. Alongside my education, I like to work on freelance projects to pay my bills and open source projects to give back. I am a huge fan on reading content related to design process and especially typography.",
        "hobbycreative": 1,
        "hobbyprogramming": 1,
        "hobbygraphics": 1,
        "hobbydesign": 1,
        "skillivis": 6,
        "skillstats": 5,
        "skillmath": 8,
        "skillart": 7,
        "skilluser": 8,
        "skillprog": 7,
        "skillgraphics": 7,
        "skillhci": 7,
        "skillux": 8,
        "group": 5,
        "groupindex": 3,
        "top": "ux",
        "learning": "I expect to be more comfortable in visually interpreting huge amount of data. I am comfortable with d3 but would like to work on integrating it with WebGL, if possible."
    },
    {
        "number": 8,
        "alias": "Bofur",
        "skillivis": 4,
        "skillstats": 4,
        "skillmath": 6,
        "skillart": 5,
        "skilluser": 7,
        "skillprog": 7,
        "skillgraphics": 3,
        "skillhci": 3,
        "skillux": 2,
        "group": 8,
        "groupindex": 2,
        "top": "math",
        "learning": "I expect that at the end of the course I'll be able to create information visualisation systems for complex data which will make it easier to read and comprehend. Since my specialisation track is Data Science, it will be a good skill to have. "
    },
    {
        "number": 9,
        "alias": "Bombadil",
        "hobbytext": "travel, sports, running, yoga, cycling, photography, coffee, gender equality, diversity, education, human rights",
        "hobbycreative": 1,
        "hobbyphysical": 4,
        "hobbytravel": 1,
        "hobbysociety": 3,
        "hobbyeducation": 1,
        "skillivis": 4,
        "skillstats": 6,
        "skillmath": 6,
        "skillart": 2,
        "skilluser": 6,
        "skillprog": 5,
        "skillgraphics": 1,
        "skillhci": 5,
        "skillux": 8,
        "group": 2,
        "groupindex": 1,
        "top": "ux",
        "learning": "I am hoping to learn a lot of practical skills (e.g. different tools that can be used for visualization) as well as the theory of what is \"good\" visualization. I am extremely interested in using information visualization to help people better understand concepts (I have been a big fan of the New York Times digital team even before the first class)."
    },
    {
        "number": 10,
        "alias": "Bombur",
        "hobbytext": "I like football and play on the school team. I also like painting, illustrating and programming.",
        "hobbycreative": 2,
        "hobbyphysical": 1,
        "hobbyprogramming": 1,
        "skillivis": 1,
        "skillstats": 4,
        "skillmath": 5,
        "skillart": 10,
        "skilluser": 7,
        "skillprog": 4,
        "skillgraphics": 2,
        "skillhci": 3,
        "skillux": 6,
        "group": 1,
        "groupindex": 2,
        "top": "art",
        "learning": "To get to know different tools for visualizing information and to know how to choose what information to be shown."
    },
    {
        "number": 11,
        "alias": "Borin",
        "hobbytext": "Reading, music, arts, bikes, travel, technology, programming, humor.",
        "hobbycreative": 2,
        "hobbyphysical": 1,
        "hobbytech": 1,
        "hobbymedia": 1,
        "hobbyprogramming": 1,
        "hobbytravel": 1,
        "skillivis": 2,
        "skillstats": 4,
        "skillmath": 2,
        "skillart": 6,
        "skilluser": 6,
        "skillprog": 2,
        "skillgraphics": 1,
        "skillhci": 4,
        "skillux": 10,
        "group": 10,
        "groupindex": 2,
        "top": "ux",
        "learning": "Techniques: How to create Trees and Networks. What are Dynamic Queries. What is Interactive Data Analysis. How to visualize Overview and Detail. What are Fisheye Views. What is a Bifocal Lens. What a Visual Transfer Function. How to Map Data in 1D, 2D and 3D. How to use Color. How to create Angular Treemaps. What are Edge Equalized Treemaps. What is the Forest Metaphor. \nProgramming: What is D3 and how to use it. How to use JSON for Geomapping. Can I understand Phython, Map/Reduce, and Hadoop as non-mathetician and is it actually necessary? \nMeaning: How to get a Big Picture through Searching and Discovery. How to tell a Visual Story from a Questions, Visual Data and Context. How really enhance Human Cognition and not just do eye-candy-beautification.\nApplication: Can I visualize Financial Flows (e.g., into Tax Haven Destinations) and relevant Triggers (i.e., human actors, companies, banks), animate this so I can also visualize consequences of these flows, short- and long-term, extrapolated into the Future. Why: to enable understanding and support Decision Making (one idea).\nInput: Where to get all the data from and not repeat trivial relationships in a more beauty way."
    },
    {
        "number": 12,
        "alias": "Boromir",
        "hobbytext": "Web Development, Competitive Programming, Data Science (Machine learning)",
        "hobbyprogramming": 3,
        "skillivis": 3,
        "skillstats": 5,
        "skillmath": 5,
        "skillart": 1,
        "skilluser": 7,
        "skillprog": 8,
        "skillgraphics": 2,
        "skillhci": 6,
        "skillux": 5,
        "group": 9,
        "groupindex": 1,
        "top": "prog",
        "learning": "Learn technique to display high dimensional data in an intuitive manner.\nUtilize D3.js to implement some modern visualizations, and perhaps create some of my own."
    },
    {
        "number": 13,
        "alias": "Bounder",
        "hobbytext": "Arts and culture, education, science and technology",
        "hobbycreative": 1,
        "hobbytech": 1,
        "hobbyscience": 1,
        "hobbyculture": 1,
        "hobbyeducation": 1,
        "skillivis": 3,
        "skillstats": 9,
        "skillmath": 9,
        "skillart": 3,
        "skilluser": 10,
        "skillprog": 10,
        "skillgraphics": 3,
        "skillhci": 3,
        "skillux": 9,
        "group": 8,
        "groupindex": 3,
        "top": "ux",
        "learning": "A whole thorough workflow of information visualization from scratch to the end."
    },
    {
        "number": 14,
        "alias": "Celeborn",
        "hobbytext": "I'm interested in digital democracy, digital literacy, accessibility, usability and those kinds of questions. I also like stuff like tv-shows, travelling and cooking food.",
        "hobbymedia": 1,
        "hobbyfood": 1,
        "hobbypolitics": 1,
        "hobbysociety": 3,
        "skillivis": 7,
        "skillstats": 6,
        "skillmath": 5,
        "skillart": 6,
        "skilluser": 8,
        "skillprog": 4,
        "skillgraphics": 1,
        "skillhci": 6,
        "skillux": 7,
        "group": 2,
        "groupindex": 2,
        "top": "ivis",
        "learning": "I think information visualisation is a powerful tool (that is on the rise) in order to help people understand different kinds of connections and causes. Especielly in a world of big data, this feels really relevant. I expect to learn how to present information depending on the data, i.e. what kind of data you have determines how you visualise it - not all kinds of data fits in the same kind of visualisation."
    },
    {
        "number": 15,
        "alias": "Damrod",
        "skillivis": 3,
        "skillstats": 2,
        "skillmath": 5,
        "skillart": 6,
        "skilluser": 7,
        "skillprog": 1,
        "skillgraphics": 2,
        "skillhci": 3,
        "skillux": 8,
        "group": 5,
        "groupindex": 4,
        "top": "math",
        "learning": "I want to learn more about how to use visualization as a tool in interaction design and improve my skills in simplifying, personalizing and presenting data. As an interaction designer, I believe that a better knowledge of visualization will be very helpful for my further studies.  "
    },
    {
        "number": 16,
        "alias": "Deagol",
        "hobbytext": "Reading, magic(illusions), training, nature",
        "hobbyphysical": 1,
        "hobbymedia": 1,
        "skillivis": 1,
        "skillstats": 3,
        "skillmath": 3,
        "skillart": 5,
        "skilluser": 8,
        "skillprog": 5,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 2,
        "group": 2,
        "groupindex": 3,
        "top": "user",
        "learning": "Learn to display data (possibly in many dimensions) in a clear way."
    },
    {
        "number": 17,
        "alias": "Denethor",
        "skillivis": 7,
        "skillstats": 8,
        "skillmath": 6,
        "skillart": 2,
        "skilluser": 8,
        "skillprog": 9,
        "skillgraphics": 6,
        "skillhci": 3,
        "skillux": 6,
        "group": 3,
        "groupindex": 1,
        "top": "ivis",
        "learning": " I hope I could learn some fancy skills in visualization and make out some useful visualization system"
    },
    {
        "number": 18,
        "alias": "Dorlas",
        "skillivis": 4,
        "skillstats": 4,
        "skillmath": 4,
        "skillart": 6,
        "skilluser": 5,
        "skillprog": 4,
        "skillgraphics": 1,
        "skillhci": 5,
        "skillux": 6,
        "group": 7,
        "groupindex": 1,
        "top": "hci",
        "learning": "I want to learn how to visualize \"boring\" data to make it fun, interactive and interesting. I would like to learn more about programming since it was a while ago I coded. "
    },
    {
        "number": 19,
        "alias": "Dwalin",
        "hobbytext": "I'm interested in music, dance, traveling, and more.",
        "hobbycreative": 2,
        "hobbytravel": 1,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 6,
        "skillart": 7,
        "skilluser": 7,
        "skillprog": 6,
        "skillgraphics": 1,
        "skillhci": 5,
        "skillux": 5,
        "group": 7,
        "groupindex": 2,
        "top": "art",
        "learning": "Expect to learn how to visualize information in a good way.  Expect to use the knowledge when working in the future."
    },
    {
        "number": 20,
        "alias": "Eldarion",
        "hobbytext": "Play music & watch sports",
        "hobbycreative": 1,
        "hobbyphysical": 1,
        "skillivis": 3,
        "skillstats": 4,
        "skillmath": 9,
        "skillart": 8,
        "skilluser": 8,
        "skillprog": 3,
        "skillgraphics": 2,
        "skillhci": 8,
        "skillux": 9,
        "group": 7,
        "groupindex": 3,
        "top": "ux",
        "learning": "How to best present information based on what, where, when, for who etc. "
    },
    {
        "number": 21,
        "alias": "Elendil",
        "hobbytext": "I like being creative, mostly with computers and programs. I've spend a lot of time the recent years doing code, illustrations, 3D-models any much more. I also love consuming stories in the forms of books, games and movies.",
        "hobbycreative": 1,
        "hobbymedia": 2,
        "hobbygames": 1,
        "hobbyprogramming": 1,
        "hobbygraphics": 1,
        "skillivis": 5,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 6,
        "skilluser": 7,
        "skillprog": 7,
        "skillgraphics": 4,
        "skillhci": 6,
        "skillux": 5,
        "group": 5,
        "groupindex": 5,
        "top": "prog",
        "learning": "I expect to learn more about what forms of visualizations that are popular and effective and also be able to choose what form of visualization fits best for what type of data. I hope to be able to create these visualizations myself by code."
    },
    {
        "number": 22,
        "alias": "Elendur",
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 2,
        "skilluser": 7,
        "skillprog": 5,
        "skillgraphics": 2,
        "skillhci": 6,
        "skillux": 9,
        "group": 6,
        "groupindex": 1,
        "top": "ux",
        "learning": "How you can visualise thing in clear and understandable ways for a user, making  information more easy to understand"
    },
    {
        "number": 23,
        "alias": "Elrond",
        "hobbytext": "Skiing, Computer Games, Working out at the gym, Programming.",
        "hobbyphysical": 2,
        "hobbygames": 1,
        "hobbyprogramming": 1,
        "skillivis": 3,
        "skillstats": 10,
        "skillmath": 8,
        "skillart": 1,
        "skilluser": 6,
        "skillprog": 9,
        "skillgraphics": 4,
        "skillhci": 3,
        "skillux": 3,
        "group": 5,
        "groupindex": 6,
        "top": "stats",
        "learning": "How to visualize results from different statistical and heuristic methods so that non experts, eg. customers, boss, colleges ,can understand."
    },
    {
        "number": 24,
        "alias": "Eomer",
        "hobbytext": "Interested in art and music (as a hobby), machine learning (academically). ",
        "hobbycreative": 2,
        "hobbyprogramming": 1,
        "skillivis": 7,
        "skillstats": 9,
        "skillmath": 7,
        "skillart": 3,
        "skilluser": 9,
        "skillprog": 8,
        "skillgraphics": 7,
        "skillhci": 6,
        "skillux": 1,
        "group": 4,
        "groupindex": 2,
        "top": "ivis",
        "learning": "Various vis technique to be applied in industry and neural network."
    },
    {
        "number": 25,
        "alias": "Eothain",
        "hobbytext": "Interests are music, programming and computer graphics. I'm a huge fan of old console video games, and still, nothing beats a really good platformer. I want to create stuff that people can benefit from, and hopefully make the world somewhat of a better place. ",
        "hobbycreative": 1,
        "hobbygames": 1,
        "hobbyprogramming": 1,
        "hobbygraphics": 1,
        "skillivis": 5,
        "skillstats": 5,
        "skillmath": 7,
        "skillart": 4,
        "skilluser": 9,
        "skillprog": 9,
        "skillgraphics": 8,
        "skillhci": 4,
        "skillux": 3,
        "group": 4,
        "groupindex": 3,
        "top": "prog",
        "learning": "As of today, there is \"some slight misuse\" of everything from statistic data to pure crappy data representations out in our society. After this course I want to be able to choose a good way of visualizing data (useful for more than my graduation work..) and also being able to interpret other peoples visualizations. My artistic skills are not that great, and getting a push here and practicing might be a healthy bonus."
    },
    {
        "number": 26,
        "alias": "Eowyn",
        "hobbytext": "Photography and Traveling.",
        "hobbycreative": 1,
        "hobbytravel": 1,
        "skillivis": 2,
        "skillstats": 4,
        "skillmath": 4,
        "skillart": 4,
        "skilluser": 4,
        "skillprog": 2,
        "skillgraphics": 6,
        "skillhci": 4,
        "skillux": 4,
        "group": 3,
        "groupindex": 2,
        "top": "hci",
        "learning": "I want to be able to present information in an interactive way that enables the viewer to understand the information presented."
    },
    {
        "number": 27,
        "alias": "Faramir",
        "hobbytext": "Sketching, Hacking stuff, Cooking",
        "hobbycreative": 1,
        "hobbyprogramming": 1,
        "hobbyfood": 1,
        "skillivis": 5,
        "skillstats": 4,
        "skillmath": 8,
        "skillart": 7,
        "skilluser": 9,
        "skillprog": 8,
        "skillgraphics": 5,
        "skillhci": 6,
        "skillux": 6,
        "group": 2,
        "groupindex": 4,
        "top": "prog",
        "learning": "I want better ways of expression. "
    },
    {
        "number": 28,
        "alias": "Ferny",
        "hobbytext": "Graphic design, photography, bartending",
        "hobbycreative": 1,
        "hobbygraphics": 1,
        "hobbydesign": 1,
        "skillivis": 5,
        "skillstats": 2,
        "skillmath": 3,
        "skillart": 4,
        "skilluser": 8,
        "skillprog": 5,
        "skillgraphics": 3,
        "skillhci": 4,
        "skillux": 1,
        "group": 9,
        "groupindex": 2,
        "top": "hci",
        "learning": "D3.js, how to effectively convey large amounts of information. Hopefully both at my current job and later in my career"
    },
    {
        "number": 29,
        "alias": "Fili",
        "hobbytext": "Programming, android application development.",
        "hobbyprogramming": 2,
        "skillivis": 5,
        "skillstats": 5,
        "skillmath": 5,
        "skillart": 4,
        "skilluser": 5,
        "skillprog": 5,
        "skillgraphics": 4,
        "skillhci": 5,
        "skillux": 5,
        "group": 2,
        "groupindex": 5,
        "top": "math",
        "learning": "I would like to learn more about how to visualize information and data in simple, forseeable and comprehensible ways."
    },
    {
        "number": 30,
        "alias": "Freda",
        "hobbytext": "Startups and arts especially photography",
        "hobbycreative": 2,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 9,
        "skillart": 7,
        "skilluser": 7,
        "skillprog": 2,
        "skillgraphics": 2,
        "skillhci": 3,
        "skillux": 8,
        "group": 1,
        "groupindex": 3,
        "top": "ux",
        "learning": "Learn new and explorative ways to represent and visualise data effectively. New techniques, concepts and skills to help provide informative visuals in both academic and career prospects. "
    },
    {
        "number": 31,
        "alias": "Frodo",
        "hobbytext": "I like to work with graphics and stuff where you actually see what you're accomplishing. I like to spend time with friends and climb on my spare time ",
        "hobbyphysical": 1,
        "hobbysocial": 1,
        "hobbygraphics": 1,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 4,
        "skillart": 4,
        "skilluser": 6,
        "skillprog": 5,
        "skillgraphics": 3,
        "skillhci": 4,
        "skillux": 3,
        "group": 1,
        "groupindex": 4,
        "top": "hci",
        "learning": "Learn the basics of how you visualize big data into understandable graphs "
    },
    {
        "number": 32,
        "alias": "Galadriel",
        "hobbytext": "I have been working a programmer in the mobile space for the past 4 years before I joined master school here at KTH. I am extremely interested in how programming plays its role in creating art forms and that design married with technology can produce amazing experiences. I play basketball and enjoy equestrian sports a lot. I code on hobby projects when I am free and that had led me to pursue a startup earlier as well.",
        "hobbycreative": 1,
        "hobbyphysical": 1,
        "hobbyprogramming": 1,
        "skillivis": 7,
        "skillstats": 5,
        "skillmath": 6,
        "skillart": 7,
        "skilluser": 9,
        "skillprog": 8,
        "skillgraphics": 7,
        "skillhci": 8,
        "skillux": 5,
        "group": 5,
        "groupindex": 7,
        "top": "ivis",
        "learning": "I intend to understand and produce brilliant information projects that can be used to understand the knowledge that is there over the internet. I intend to apply and publish information that is meaningful. I have tried to present such information from twitter feed etc but I have lacked in creating truly relevant and meaningful content. I hope to review and correct my short comings."
    },
    {
        "number": 33,
        "alias": "Gamgee",
        "hobbytext": "I like playing computer games and hanging with my girlfriend",
        "hobbygames": 1,
        "skillivis": 2,
        "skillstats": 4,
        "skillmath": 6,
        "skillart": 2,
        "skilluser": 7,
        "skillprog": 6,
        "skillgraphics": 2,
        "skillhci": 4,
        "skillux": 3,
        "group": 7,
        "groupindex": 4,
        "top": "math",
        "learning": "I wish to learn more about how to think when making design choices as well as how to implement them."
    },
    {
        "number": 34,
        "alias": "Gandalf",
        "skillivis": 4,
        "skillstats": 6,
        "skillmath": 8,
        "skillart": 1,
        "skilluser": 9,
        "skillprog": 8,
        "skillgraphics": 6,
        "skillhci": 5,
        "skillux": 5,
        "group": 1,
        "groupindex": 5,
        "top": "stats",
        "learning": "I expect to learn fun and innovative ways of representing data. I plan on using the skills I learn in future presentation and possibly my personal portfolio."
    },
    {
        "number": 35,
        "alias": "Gimli",
        "hobbytext": "Diving, wildlife and painting",
        "hobbycreative": 1,
        "hobbyphysical": 2,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 4,
        "skillart": 9,
        "skilluser": 7,
        "skillprog": 1,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 1,
        "group": 3,
        "groupindex": 3,
        "top": "art",
        "learning": "\nApply my interest and knowledge in design and painting to become professional in making presentations and visualizations"
    },
    {
        "number": 36,
        "alias": "Gollum",
        "hobbytext": "When people ask me what interests me, I often answer saying that I am inherently curious. With that I mean I'm interest in basically everything that crosses my path, from science to arts to stupid internet things. Now, on a deeper level, academically speaking, I like to think about how technology and society interact, how this things we create end up shaping us. in fact that is the reason I left Brazil to study here. \nAs for hobbies, in my spare time lately I have been trying to learn how to code (basically JavaScript and HTML). Also, I am passionate about music (I used to play guitar and violin) and in the past months I have grown an interest on cooking. ",
        "hobbycreative": 2,
        "hobbytech": 1,
        "hobbyprogramming": 1,
        "hobbyfood": 1,
        "hobbysociety": 1,
        "skillivis": 4,
        "skillstats": 2,
        "skillmath": 2,
        "skillart": 4,
        "skilluser": 9,
        "skillprog": 1,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 6,
        "group": 1,
        "groupindex": 6,
        "top": "user",
        "learning": "I have 2 goals in the course. The first one is to understand how aesthethics and design can help people make sense of the huge amount of data we generate every second. The other is more technical, to learn tools to create such graphics and visualizations."
    },
    {
        "number": 37,
        "alias": "Gorbag",
        "hobbytext": "I did my Bachelor in Computer Engineering and worked for almost 3 years as a software developer. Even though I love programming, I realised that programming on a topic that I have no interest in, is really depressing. So I applied to KTH and moved to Stockholm to learn more about a topic I'm interested on programming.\n\nI like playing video games in my free time. I can be found browsing Steam for survival, city-building games or indie games. I follow most of AAA titles too. I also watch movies, tv-series and read books. And recently, I got inspirited by a book I've read and started baking cookies (random :) ) . ",
        "hobbymedia": 3,
        "hobbygames": 1,
        "hobbyfood": 1,
        "skillivis": 5,
        "skillstats": 2,
        "skillmath": 5,
        "skillart": 5,
        "skilluser": 9,
        "skillprog": 7,
        "skillgraphics": 3,
        "skillhci": 6,
        "skillux": 3,
        "group": 4,
        "groupindex": 4,
        "top": "math",
        "learning": "I find the idea of transforming a huge data to easily understandable and visually stunning graphics really interesting. I want to learn how to make visualizations, how to group the data, learn about the related math topics and make visulalizations that can chance people's perspectives and mindsets.\n\nI think that visulization can be used for almost anything since everything can be used as data. I don't know if I will be inspired enough to use it in personal projects but I want to :) I would love to learn how to use visulization in my future work too."
    },
    {
        "number": 38,
        "alias": "Grimbold",
        "hobbytext": "Cooking, eating, enjoying beer",
        "hobbyfood": 3,
        "skillivis": 4,
        "skillstats": 4,
        "skillmath": 7,
        "skillart": 5,
        "skilluser": 9,
        "skillprog": 6,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 4,
        "group": 9,
        "groupindex": 3,
        "top": "math",
        "learning": "How to properly portray data using visualization techniques. Common pitfalls when illustrating statistics. And common ways that people manipulate their agenda through data."
    },
    {
        "number": 39,
        "alias": "Grishnakh",
        "hobbytext": "Machine Learning and drinking beer",
        "hobbysocial": 1,
        "hobbyprogramming": 1,
        "skillivis": 5,
        "skillstats": 8,
        "skillmath": 6,
        "skillart": 2,
        "skilluser": 7,
        "skillprog": 8,
        "skillgraphics": 5,
        "skillhci": 4,
        "skillux": 3,
        "group": 9,
        "groupindex": 4,
        "top": "stats",
        "learning": "To be able to provide useful visualizations of machine learning solutions"
    },
    {
        "number": 40,
        "alias": "Haldir",
        "hobbytext": "Kitesurfing, Freediving, Surfing, Skiing and Product Development ",
        "hobbyphysical": 4,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 4,
        "skillart": 7,
        "skilluser": 8,
        "skillprog": 2,
        "skillgraphics": 1,
        "skillhci": 2,
        "skillux": 2,
        "group": 9,
        "groupindex": 5,
        "top": "art",
        "learning": "I would love to learn more about Interactive Design and new softwares. I'm going to use it for product presentations."
    },
    {
        "number": 41,
        "alias": "Haleth",
        "hobbytext": "I'm interested in HCI and front end programming. My hobbies are reading and watching youtube. ",
        "hobbymedia": 2,
        "hobbyprogramming": 1,
        "skillivis": 2,
        "skillstats": 3,
        "skillmath": 3,
        "skillart": 4,
        "skilluser": 6,
        "skillprog": 3,
        "skillgraphics": 1,
        "skillhci": 4,
        "skillux": 5,
        "group": 2,
        "groupindex": 6,
        "top": "hci",
        "learning": "How to visualize data in a good and easily comprehensible way "
    },
    {
        "number": 42,
        "alias": "Hama",
        "hobbytext": "Have basic knowledge about C C++ and program softeware ex. UE4, unity, visual studio",
        "hobbyprogramming": 1,
        "skillivis": 7,
        "skillstats": 8,
        "skillmath": 8,
        "skillart": 7,
        "skilluser": 9,
        "skillprog": 8,
        "skillgraphics": 8,
        "skillhci": 7,
        "skillux": 8,
        "group": 6,
        "groupindex": 2,
        "top": "ivis",
        "learning": "practice my programming skills and abilities to use different softwares. Enrich my experience for graphics."
    },
    {
        "number": 43,
        "alias": "Hardang",
        "skillivis": 2,
        "skillstats": 4,
        "skillmath": 7,
        "skillart": 9,
        "skilluser": 7,
        "skillprog": 2,
        "skillgraphics": 2,
        "skillhci": 3,
        "skillux": 8,
        "group": 2,
        "groupindex": 7,
        "top": "art",
        "learning": "I expect to learn how to use D3 or other technology for visualize the specific data which I want to show to other people  or related to my study for having better imagination of data. "
    },
    {
        "number": 44,
        "alias": "Idril",
        "skillivis": 6,
        "skillstats": 3,
        "skillmath": 3,
        "skillart": 8,
        "skilluser": 10,
        "skillprog": 5,
        "skillgraphics": 3,
        "skillhci": 5,
        "skillux": 5,
        "group": 4,
        "groupindex": 5,
        "top": "art",
        "learning": "I want to learn some web visualization skills"
    },
    {
        "number": 45,
        "alias": "Irolas",
        "hobbytext": "Astronomy, virtual reality, gaming, music",
        "hobbycreative": 1,
        "hobbygames": 1,
        "skillivis": 5,
        "skillstats": 4,
        "skillmath": 5,
        "skillart": 2,
        "skilluser": 7,
        "skillprog": 7,
        "skillgraphics": 4,
        "skillhci": 6,
        "skillux": 5,
        "group": 6,
        "groupindex": 3,
        "top": "prog",
        "learning": "Programming, virtual/mixed reality. Be able to decipher data easier and work with virtual reality and gaming."
    },
    {
        "number": 46,
        "alias": "Isildur",
        "hobbytext": "Game development, creating music, creative work",
        "hobbycreative": 3,
        "skillivis": 4,
        "skillstats": 5,
        "skillmath": 5,
        "skillart": 4,
        "skilluser": 8,
        "skillprog": 8,
        "skillgraphics": 3,
        "skillhci": 5,
        "skillux": 5,
        "group": 1,
        "groupindex": 7,
        "top": "prog",
        "learning": "I want to learn how to display complex information in a very simple and understanding way. I  wish to use this knowledge to display complex relations in games to help players understand the consequences of their actions."
    },
    {
        "number": 47,
        "alias": "Kili",
        "hobbytext": "Watch documentaries, badminton, food",
        "hobbyphysical": 1,
        "hobbymedia": 1,
        "hobbyfood": 1,
        "skillivis": 3,
        "skillstats": 5,
        "skillmath": 5,
        "skillart": 1,
        "skilluser": 6,
        "skillprog": 6,
        "skillgraphics": 3,
        "skillhci": 5,
        "skillux": 8,
        "group": 3,
        "groupindex": 4,
        "top": "stats",
        "learning": "I will learn to analyze data and present in a thoughtful way that the reader understands it and perceives it correctly. I will use it in future project where I will have to present data and the analytical skills will be useful in my everyday life."
    },
    {
        "number": 48,
        "alias": "Legolas",
        "hobbytext": "Already work as developer for 8 years, full-stack, mostly front-end. I like developing web applications with new technologies (angularjs, bootstrap,...). Hobbies are: football, hunting & woodcrafting.",
        "hobbyphysical": 2,
        "hobbyprogramming": 1,
        "skillivis": 4,
        "skillstats": 4,
        "skillmath": 4,
        "skillart": 7,
        "skilluser": 8,
        "skillprog": 8,
        "skillgraphics": 4,
        "skillhci": 4,
        "skillux": 4,
        "group": 10,
        "groupindex": 3,
        "top": "prog",
        "learning": "Different approaches to present different data and tell a story with that data, and also methods and frameworks to do it."
    },
    {
        "number": 49,
        "alias": "Lindir",
        "hobbytext": "I like photography and to play music. I like good design and functional tecnology. ",
        "hobbycreative": 2,
        "hobbytech": 1,
        "hobbydesign": 1,
        "skillivis": 2,
        "skillstats": 2,
        "skillmath": 5,
        "skillart": 2,
        "skilluser": 7,
        "skillprog": 4,
        "skillgraphics": 1,
        "skillhci": 4,
        "skillux": 4,
        "group": 10,
        "groupindex": 4,
        "top": "hci",
        "learning": "To learn some basic technology how to visualize data and how to do that in a meaningful way. I like the idea of that we are creating mental images of information as I find this very effective. I hope I can use it it my future profession. "
    },
    {
        "number": 50,
        "alias": "Lurtz",
        "hobbytext": "rock climbing, reading, drinking coffee",
        "hobbyphysical": 1,
        "hobbymedia": 1,
        "skillivis": 3,
        "skillstats": 6,
        "skillmath": 7,
        "skillart": 6,
        "skilluser": 8,
        "skillprog": 8,
        "skillgraphics": 3,
        "skillhci": 4,
        "skillux": 5,
        "group": 2,
        "groupindex": 8,
        "top": "stats",
        "learning": "I expect to learn best strategies for displaying information in intuitive and interactive ways. I'd like to be able to create visualizations that prompt users to ask questions about their data. I expect to learn through lectures and experimenting with different layouts myself. "
    },
    {
        "number": 51,
        "alias": "Madril",
        "hobbytext": "I like photography, music and new technology / technology related services/products.",
        "hobbycreative": 2,
        "hobbytech": 1,
        "skillivis": 4,
        "skillstats": 4,
        "skillmath": 5,
        "skillart": 4,
        "skilluser": 9,
        "skillprog": 5,
        "skillgraphics": 2,
        "skillhci": 7,
        "skillux": 5,
        "group": 1,
        "groupindex": 8,
        "top": "math",
        "learning": "I expect to learn how to use different libraries to code and visualize large amounts of data in a educational way that is easy to perceive. "
    },
    {
        "number": 52,
        "alias": "Maiar",
        "hobbytext": "I like programming (outside of school) when I get the time. As of late I have also become interested in savings/stocks and so on (still a novice though, but it can be fun at times). Other than that I like to paint (everything from walls to sketching a Disney character), used to play football but injuries happen so had to quit. ",
        "hobbycreative": 1,
        "hobbyphysical": 1,
        "hobbyprogramming": 1,
        "skillivis": 6,
        "skillstats": 5,
        "skillmath": 5,
        "skillart": 7,
        "skilluser": 7,
        "skillprog": 4,
        "skillgraphics": 2,
        "skillhci": 5,
        "skillux": 6,
        "group": 4,
        "groupindex": 6,
        "top": "stats",
        "learning": "What type of visualization goes with what \"kind\" of data, how you should think in terms of inteded users/audience. How to program interactive programs and using for example D3.js. <- very interested in that part, you can make some cool things. I think I will be able to use everything I learn in this course in future projects and later at work."
    },
    {
        "number": 53,
        "alias": "Mauhur",
        "hobbytext": "I always strive for progress, as a person and for my skills. I currently want to learn a lot about programming! My other interests are reading, socializing, drawing & computer games ",
        "hobbycreative": 1,
        "hobbymedia": 1,
        "hobbygames": 1,
        "hobbypsychology": 1,
        "hobbysocial": 1,
        "hobbyprogramming": 1,
        "skillivis": 7,
        "skillstats": 2,
        "skillmath": 5,
        "skillart": 8,
        "skilluser": 9,
        "skillprog": 6,
        "skillgraphics": 2,
        "skillhci": 6,
        "skillux": 7,
        "group": 7,
        "groupindex": 5,
        "top": "ivis",
        "learning": "Which techniques to visualize information works better for which situations. Also I'd like to learn more tools to visualize information (like d3.js) I expect to keep these skills for a long time and that they help me be more awesome in my future career "
    },
    {
        "number": 54,
        "alias": "Merry",
        "hobbytext": "I like exploring the world and face challenges. I love drawing and cooking. ",
        "hobbycreative": 1,
        "hobbypsychology": 1,
        "hobbytravel": 1,
        "hobbyfood": 1,
        "skillivis": 5,
        "skillstats": 6,
        "skillmath": 7,
        "skillart": 8,
        "skilluser": 7,
        "skillprog": 6,
        "skillgraphics": 4,
        "skillhci": 4,
        "skillux": 8,
        "group": 3,
        "groupindex": 5,
        "top": "ux",
        "learning": "I am expecting to learn different ways of visualising and interacting with data which will help me to show and engage my product users and clients with precise information rather than assumptions when I become designer. "
    },
    {
        "number": 55,
        "alias": "Morwen",
        "hobbytext": "I'm very active in sports.  I'm practicing a sport called trampoline which I do at an elite level meaning I'm in the national team of Sweden and I get to compete in Nordic, European and World Championships. Apart from sports I play video games,  I fiddle around in Unity and compose as well as produce music on my own using Propellerheads Reason DAW. I like to learn a little about everything. ",
        "hobbycreative": 1,
        "hobbyphysical": 2,
        "hobbygames": 1,
        "skillivis": 3,
        "skillstats": 5,
        "skillmath": 4,
        "skillart": 3,
        "skilluser": 10,
        "skillprog": 6,
        "skillgraphics": 2,
        "skillhci": 7,
        "skillux": 5,
        "group": 6,
        "groupindex": 4,
        "top": "hci",
        "learning": "I want to learn how to make an intuitive, well-designed representation of information that is of course visualized. I think what is learnt here can be used in many different contexts. I see that's it's about making sense of data, and in for example counter strike global offensive, you have lots of data that you can get from the game demos but the ways of representing it is limited. "
    },
    {
        "number": 56,
        "alias": "Nessa",
        "hobbytext": "Interested in design. Also interested in incorporating environmental beneficial media technology artefacts in homes and businesses (wrote my bachelor thesis about Smart homes), that's one of the reasons I chose this course. In my spare time I photograph and film for fun. ",
        "hobbycreative": 1,
        "hobbydesign": 1,
        "skillivis": 1,
        "skillstats": 1,
        "skillmath": 1,
        "skillart": 2,
        "skilluser": 2,
        "skillprog": 1,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 2,
        "group": 4,
        "groupindex": 7,
        "top": "user",
        "learning": "I want to learn more about graphic design, data representation, user-centered design, and information design. I'm interested to find out if this is something I want to work with in the future."
    },
    {
        "number": 57,
        "alias": "Ohtar",
        "hobbytext": "My interests are technology, science, computers, games, nature and fitness.",
        "hobbyphysical": 1,
        "hobbytech": 1,
        "hobbygames": 1,
        "hobbyscience": 1,
        "skillivis": 2,
        "skillstats": 2,
        "skillmath": 1,
        "skillart": 3,
        "skilluser": 4,
        "skillprog": 4,
        "skillgraphics": 1,
        "skillhci": 2,
        "skillux": 2,
        "group": 3,
        "groupindex": 6,
        "top": "user",
        "learning": "I would like to learn more how rendering works and how I can present data in a dynamic way to get the best user experience. I'm going to use the skills I learn when I in the future develop different kinds of applications."
    },
    {
        "number": 58,
        "alias": "Oin",
        "hobbytext": "Music, piano, asian culture",
        "hobbycreative": 2,
        "hobbyculture": 1,
        "skillivis": 7,
        "skillstats": 5,
        "skillmath": 8,
        "skillart": 5,
        "skilluser": 8,
        "skillprog": 9,
        "skillgraphics": 7,
        "skillhci": 9,
        "skillux": 7,
        "group": 8,
        "groupindex": 4,
        "top": "ivis",
        "learning": "I expect to learn how to design an optimal and effective information visualization system depending on the type of data to represent and the user context."
    },
    {
        "number": 59,
        "alias": "Otho",
        "skillivis": 6,
        "skillstats": 3,
        "skillmath": 4,
        "skillart": 6,
        "skilluser": 10,
        "skillprog": 7,
        "skillgraphics": 5,
        "skillhci": 9,
        "skillux": 7,
        "group": 7,
        "groupindex": 6,
        "top": "prog",
        "learning": "Solid theory about visualizing datasets that I can apply in future work."
    },
    {
        "number": 60,
        "alias": "Pelendur",
        "hobbytext": "Drumset",
        "hobbycreative": 1,
        "skillivis": 2,
        "skillstats": 5,
        "skillmath": 4,
        "skillart": 3,
        "skilluser": 4,
        "skillprog": 5,
        "skillgraphics": 4,
        "skillhci": 4,
        "skillux": 1,
        "group": 4,
        "groupindex": 8,
        "top": "hci",
        "learning": "How to make visualization like informationisbeautiful.com . I expect to learn it through practicing the methods taught in the course"
    },
    {
        "number": 61,
        "alias": "Pippin",
        "hobbytext": "Art, design, computer games, programming",
        "hobbycreative": 1,
        "hobbygames": 1,
        "hobbyprogramming": 1,
        "hobbydesign": 1,
        "skillivis": 7,
        "skillstats": 2,
        "skillmath": 2,
        "skillart": 8,
        "skilluser": 10,
        "skillprog": 7,
        "skillgraphics": 2,
        "skillhci": 5,
        "skillux": 2,
        "group": 9,
        "groupindex": 6,
        "top": "ivis",
        "learning": "As the course name states, learn how to visualize information and data. I want to improve myself in the field of visualization."
    },
    {
        "number": 62,
        "alias": "Quickbeam",
        "hobbytext": "I am interested in design overall, both product design and graphic design. Beside my studies, I am working as Art Director for the THS Union Sports Association. I am also helping small companies with logos and some printed material. In my spare time I work in a mens clothing store, I travel as much as I can and I also try to photograph as much as I can on my travels. I have an older brother that I think you might recognize a graduated KTH student whos visualization skills I'm trying to learn from. ",
        "hobbycreative": 1,
        "hobbytravel": 1,
        "hobbydesign": 1,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 8,
        "skilluser": 8,
        "skillprog": 2,
        "skillgraphics": 3,
        "skillhci": 3,
        "skillux": 3,
        "group": 6,
        "groupindex": 5,
        "top": "art",
        "learning": "My expectation is to learn how to use my graphic design skills in combination with programming in order to create the visualization ideas that I have but not have the tools to create. I also hope to get a glimps in web design, and how to create websites."
    },
    {
        "number": 63,
        "alias": "Rian",
        "hobbytext": "I'm a huge gamer, love boardgames and videogames. Also pretty big into art in general, books and movies and music.",
        "hobbycreative": 1,
        "hobbymedia": 2,
        "hobbygames": 2,
        "skillivis": 3,
        "skillstats": 5,
        "skillmath": 5,
        "skillart": 2,
        "skilluser": 8,
        "skillprog": 5,
        "skillgraphics": 3,
        "skillhci": 4,
        "skillux": 4,
        "group": 8,
        "groupindex": 5,
        "top": "hci",
        "learning": "Don't know exactly, but how to present data and information in a good way "
    },
    {
        "number": 64,
        "alias": "Sam",
        "skillivis": 6,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 9,
        "skilluser": 8,
        "skillprog": 4,
        "skillgraphics": 4,
        "skillhci": 4,
        "skillux": 9,
        "group": 9,
        "groupindex": 7,
        "top": "ux",
        "learning": "Better describe data from individual perspective "
    },
    {
        "number": 65,
        "alias": "Sauron",
        "hobbytext": "Sports, dancing, hiking, travelling",
        "hobbyphysical": 3,
        "hobbytravel": 1,
        "skillivis": 3,
        "skillstats": 9,
        "skillmath": 7,
        "skillart": 2,
        "skilluser": 9,
        "skillprog": 6,
        "skillgraphics": 5,
        "skillhci": 3,
        "skillux": 3,
        "group": 6,
        "groupindex": 6,
        "top": "stats",
        "learning": "We now that a good code behind is not what makes the customers buy the product. In fact it is the graphical interface. Still, design and visualization is not taught really. I know how to do backend, but nothing about frontend. That is why I am here. "
    },
    {
        "number": 66,
        "alias": "Shagrat",
        "hobbytext": "Sports, movies and tv-series, art.",
        "hobbycreative": 1,
        "hobbyphysical": 1,
        "hobbymedia": 2,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 6,
        "skilluser": 7,
        "skillprog": 2,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 4,
        "group": 6,
        "groupindex": 7,
        "top": "math",
        "learning": "To learn how to present data in a estethically and interactive way. Hopefully this could be used when presenting research results in future projects and work. "
    },
    {
        "number": 67,
        "alias": "Sharku",
        "skillivis": 2,
        "skillstats": 7,
        "skillmath": 5,
        "skillart": 4,
        "skilluser": 6,
        "skillprog": 1,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 8,
        "group": 10,
        "groupindex": 5,
        "top": "stats",
        "learning": "I expect to learn different ways of representing data."
    },
    {
        "number": 68,
        "alias": "Smaug",
        "hobbytext": "Technologies, innovation, creating a product not only being fancy but also useful.",
        "hobbytech": 1,
        "skillivis": 7,
        "skillstats": 4,
        "skillmath": 4,
        "skillart": 6,
        "skilluser": 10,
        "skillprog": 8,
        "skillgraphics": 5,
        "skillhci": 7,
        "skillux": 6,
        "group": 3,
        "groupindex": 7,
        "top": "prog",
        "learning": "To create platforms or products in order to visualize data."
    },
    {
        "number": 69,
        "alias": "Smeagol",
        "hobbytext": "History and statistics, video games and films, digital painting, cooking.",
        "hobbycreative": 1,
        "hobbymedia": 1,
        "hobbygames": 1,
        "hobbyfood": 1,
        "skillivis": 3,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 7,
        "skilluser": 9,
        "skillprog": 3,
        "skillgraphics": 2,
        "skillhci": 3,
        "skillux": 8,
        "group": 8,
        "groupindex": 6,
        "top": "art",
        "learning": "How to process data and provide information in ways that make it accessible while allowing for multiple realizations as you spend time with it."
    },
    {
        "number": 70,
        "alias": "Theoden",
        "hobbytext": "Creative designs and ideas in Computer Games or Applications. \nNo hobbies but am interested in many things.",
        "hobbygames": 1,
        "hobbydesign": 1,
        "skillivis": 3,
        "skillstats": 5,
        "skillmath": 8,
        "skillart": 1,
        "skilluser": 9,
        "skillprog": 2,
        "skillgraphics": 1,
        "skillhci": 1,
        "skillux": 3,
        "group": 10,
        "groupindex": 6,
        "top": "math",
        "learning": "Some useful knowledge in how to do programming in this field and how to achieve better designs. Besides, core ideas in how to correctly using visualization to convey information Intuitively and creatively."
    },
    {
        "number": 71,
        "alias": "Theodred",
        "hobbytext": "I enjoy brewing beer, playing around with OpenGL and warm weather! ",
        "hobbygraphics": 1,
        "skillivis": 4,
        "skillstats": 8,
        "skillmath": 8,
        "skillart": 5,
        "skilluser": 9,
        "skillprog": 7,
        "skillgraphics": 9,
        "skillhci": 8,
        "skillux": 4,
        "group": 8,
        "groupindex": 7,
        "top": "stats",
        "learning": "How to transform data sets of information into something that's visually comprehensive. "
    },
    {
        "number": 72,
        "alias": "Thorin",
        "hobbytext": "Music (I play guitar decently enough and am a singer, though a pretty mediocre one. And my favourite song atm is this one: https://www.youtube.com/watch?v=tlAiq0_BXac ), Photography, Hiking",
        "hobbycreative": 3,
        "hobbyphysical": 1,
        "skillivis": 7,
        "skillstats": 6,
        "skillmath": 7,
        "skillart": 2,
        "skilluser": 10,
        "skillprog": 8,
        "skillgraphics": 6,
        "skillhci": 7,
        "skillux": 7,
        "group": 10,
        "groupindex": 7,
        "top": "ivis",
        "learning": "Further my understanding of presenting data (especially interactive)\n- find out what works and doesn't in data viz\n- learn about D3.js\n- create a project where I not only learn a lot but which is also useful for my portfolio\n- have fun"
    },
    {
        "number": 73,
        "alias": "Ugluk",
        "hobbytext": "Movies, video games and ice hockey!",
        "hobbyphysical": 1,
        "hobbymedia": 1,
        "hobbygames": 1,
        "skillivis": 4,
        "skillstats": 3,
        "skillmath": 5,
        "skillart": 5,
        "skilluser": 8,
        "skillprog": 6,
        "skillgraphics": 4,
        "skillhci": 4,
        "skillux": 2,
        "group": 3,
        "groupindex": 8,
        "top": "math",
        "learning": "I expect to learn the hidden tips and tricks behind information visualization that is not obvious for the untrained eye."
    },
    {
        "number": 74,
        "alias": "Uruk",
        "hobbytext": "Gokarting, cooking, manga/anime, basketball, horror movies, reading fiction novels",
        "hobbyphysical": 2,
        "hobbymedia": 2,
        "hobbyfood": 1,
        "skillivis": 5,
        "skillstats": 8,
        "skillmath": 7,
        "skillart": 7,
        "skilluser": 9,
        "skillprog": 9,
        "skillgraphics": 8,
        "skillhci": 7,
        "skillux": 7,
        "group": 7,
        "groupindex": 7,
        "top": "stats",
        "learning": "Since, I am specializing in Data Science, I think that it would be really cool to have more skills to better visualize the data using tools like D3js (which I have never used up until now) and get to know more advanced techniques that could be used for visualizing data."
    }
]